///////////////////////////////////////////////////////////////////////////////
// RoboticsClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "RoboticsClassFactory.h"
#include "RoboticsServices.h"
#include "RoboticsVersion.h"
#include "RoboticsModule.h"

BEGIN_CLASS_MAP(CRoboticsClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_Robotics, CID_RoboticsCRoboticsModule, SRVNAME_ROBOTICS "!CRoboticsModule", CRoboticsModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CRoboticsClassFactory::CRoboticsClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_ROBOTICS));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(Robotics));
#endif //defined(TCDBG_UNIT_VERSION)
}

