///////////////////////////////////////////////////////////////////////////////
// RoboticsServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Robotics = 0x3F000000;
#define SRVNAME_ROBOTICS "Robotics"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_RoboticsCRoboticsModule = {0xdec78c84,0x5ff1,0x42ec,{0x8d,0x61,0xdf,0x08,0x5f,0x1d,0x86,0xb4}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_RoboticsModuleInputs 0
#define ADI_RoboticsModuleOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_RoboticsModuleParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _RoboticsModuleParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} RoboticsModuleParameter, *PRoboticsModuleParameter;

typedef struct _RoboticsModuleInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} RoboticsModuleInputs, *PRoboticsModuleInputs;

typedef struct _RoboticsModuleOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} RoboticsModuleOutputs, *PRoboticsModuleOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
