///////////////////////////////////////////////////////////////////////////////
// RoboticsInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "RoboticsServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
