///////////////////////////////////////////////////////////////////////////////
// SixAxisSolverClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "SixAxisSolverClassFactory.h"
#include "SixAxisSolverServices.h"
#include "SixAxisSolverVersion.h"
#include "SixAxisSolver.h"

BEGIN_CLASS_MAP(CSixAxisSolverClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_SixAxisSolver, CID_SixAxisSolverCSixAxisSolver, SRVNAME_SIXAXISSOLVER "!CSixAxisSolver", CSixAxisSolver)
///</AutoGeneratedContent>
END_CLASS_MAP()

CSixAxisSolverClassFactory::CSixAxisSolverClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_SIXAXISSOLVER));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(SixAxisSolver));
#endif //defined(TCDBG_UNIT_VERSION)
}

