///////////////////////////////////////////////////////////////////////////////
// SixAxisSolverInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "SixAxisSolverServices.h"

// this file can't be found in the sdk. it was copied from an installation of TwinCAT 4024 and placed in the project folder
// beckhoff looking into it as of 22JUL2024. for now we rock on.
#include "TcNcKinematicsInterfaces.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_05010001_0000_0000_E000_000000000064_INCLUDED_)
#define _TC_TYPE_05010001_0000_0000_E000_000000000064_INCLUDED_
struct __declspec(novtable) ITcNcTrafo : public ITcUnknown
{
	virtual HRESULT TCOMAPI Forward(TcNcTrafoParameter* p)=0;
	virtual HRESULT TCOMAPI Backward(TcNcTrafoParameter* p)=0;
	virtual HRESULT TCOMAPI TrafoSupported(TcNcTrafoParameter* p, bool fwd)=0;
	virtual HRESULT TCOMAPI GetDimensions(ULONG* pFwdInput, ULONG* pFwdOutput)=0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcNcTrafo, IID_ITcNcTrafo);
#endif // !defined(_TC_TYPE_05010001_0000_0000_E000_000000000064_INCLUDED_)

///</AutoGeneratedContent>
