///////////////////////////////////////////////////////////////////////////////
// SixAxisSolver.h
#pragma once

#include "SixAxisSolverInterfaces.h"

class CSixAxisSolver 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcNcTrafo
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CSixAxisSolver();
	virtual	~CSixAxisSolver();

///<AutoGeneratedContent id="InterfaceMembers">
	// ITcNcTrafo
	virtual HRESULT TCOMAPI Forward(TcNcTrafoParameter* p);
	virtual HRESULT TCOMAPI Backward(TcNcTrafoParameter* p);
	virtual HRESULT TCOMAPI TrafoSupported(TcNcTrafoParameter* p, bool fwd);
	virtual HRESULT TCOMAPI GetDimensions(ULONG* pFwdInput, ULONG* pFwdOutput);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

///<AutoGeneratedContent id="Members">
	AxisParameter m_Axis1Screw;
	AxisParameter m_Axis2Screw;
	AxisParameter m_Axis3Screw;
	AxisParameter m_Axis4Screw;
	AxisParameter m_Axis5Screw;
	AxisParameter m_Axis6Screw;
	EndEffectorPose m_EndEffectorHome;
///</AutoGeneratedContent>
};
