///////////////////////////////////////////////////////////////////////////////
// SixAxisSolverServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_SixAxisSolver = 0x3F000000;
#define SRVNAME_SIXAXISSOLVER "SixAxisSolver"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_SixAxisSolverCSixAxisSolver = {0x5a7dd872,0x2463,0x41ed,{0xac,0x69,0xf6,0x6a,0x78,0x4f,0x7d,0x99}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataAreaIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_05010001_0000_0000_E000_000000000064_INCLUDED_)
#define _TC_IID_05010001_0000_0000_E000_000000000064_INCLUDED_
TCOM_DECL_INTERFACE("05010001-0000-0000-e000-000000000064", ITcNcTrafo)
#endif // !defined(_TC_IID_05010001_0000_0000_E000_000000000064_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
///</AutoGeneratedContent>



///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
