///////////////////////////////////////////////////////////////////////////////
// SixAxisSolverServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_SixAxisSolver = 0x3F000000;
#define SRVNAME_SIXAXISSOLVER "SixAxisSolver"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_SixAxisSolverCSixAxisSolver = {0x5a7dd872,0x2463,0x41ed,{0xac,0x69,0xf6,0x6a,0x78,0x4f,0x7d,0x99}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataAreaIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_SixAxisSolverAxis1Screw = 0x00000002;
const PTCID PID_SixAxisSolverAxis2Screw = 0x00000003;
const PTCID PID_SixAxisSolverAxis3Screw = 0x00000004;
const PTCID PID_SixAxisSolverAxis4Screw = 0x00000005;
const PTCID PID_SixAxisSolverAxis5Screw = 0x00000006;
const PTCID PID_SixAxisSolverAxis6Screw = 0x00000007;
const PTCID PID_SixAxisSolverEndEffectorHome = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_05010001_0000_0000_E000_000000000064_INCLUDED_)
#define _TC_IID_05010001_0000_0000_E000_000000000064_INCLUDED_
TCOM_DECL_INTERFACE("05010001-0000-0000-e000-000000000064", ITcNcTrafo)
#endif // !defined(_TC_IID_05010001_0000_0000_E000_000000000064_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_83F23191_1EF8_4889_8012_2E4FDE1A687C_INCLUDED_)
#define _TC_TYPE_83F23191_1EF8_4889_8012_2E4FDE1A687C_INCLUDED_
#pragma pack(push,1)
typedef struct _AxisParameter
{
	SHORT XAlignment;
	SHORT YAlignment;
	SHORT ZAlignment;
	double XDisplacement;
	double YDisplacement;
	double ZDisplacement;
} AxisParameter, *PAxisParameter;
#pragma pack(pop)
const GUID GUID_AxisParameter = {0x83F23191, 0x1EF8, 0x4889, {0x80, 0x12, 0x2E, 0x4F, 0xDE, 0x1A, 0x68, 0x7C}};
#endif // !defined(_TC_TYPE_83F23191_1EF8_4889_8012_2E4FDE1A687C_INCLUDED_)

#if !defined(_TC_TYPE_3FC08080_B9D8_46D9_A03F_DCE5E791704A_INCLUDED_)
#define _TC_TYPE_3FC08080_B9D8_46D9_A03F_DCE5E791704A_INCLUDED_
#pragma pack(push,1)
typedef struct _EndEffectorPose
{
	SHORT XXAlignment;
	SHORT XYAlignment;
	SHORT XZAlignment;
	SHORT YXAlignment;
	SHORT YYAlignment;
	SHORT YZAlignment;
	SHORT ZXAlignment;
	SHORT ZYAlignment;
	SHORT ZZAlignment;
	double XDisplacement;
	double YDisplacement;
	double ZDisplacement;
} EndEffectorPose, *PEndEffectorPose;
#pragma pack(pop)
const GUID GUID_EndEffectorPose = {0x3FC08080, 0xB9D8, 0x46D9, {0xA0, 0x3F, 0xDC, 0xE5, 0xE7, 0x91, 0x70, 0x4A}};
#endif // !defined(_TC_TYPE_3FC08080_B9D8_46D9_A03F_DCE5E791704A_INCLUDED_)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
