///////////////////////////////////////////////////////////////////////////////
// KinematicsInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "KinematicsServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
