///////////////////////////////////////////////////////////////////////////////
// KinematicsClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "KinematicsClassFactory.h"
#include "KinematicsServices.h"
#include "KinematicsVersion.h"
#include "KinematicsModule.h"

BEGIN_CLASS_MAP(CKinematicsClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_Kinematics, CID_KinematicsCKinematicsModule, SRVNAME_KINEMATICS "!CKinematicsModule", CKinematicsModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CKinematicsClassFactory::CKinematicsClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_KINEMATICS));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(Kinematics));
#endif //defined(TCDBG_UNIT_VERSION)
}

