///////////////////////////////////////////////////////////////////////////////
// SixAxisArticulatedTrafo.h
#pragma once

#include "TC_DriverInterfaces.h"

class CSixAxisArticulatedTrafo 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcNcTrafo
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CSixAxisArticulatedTrafo();
	virtual	~CSixAxisArticulatedTrafo();

///<AutoGeneratedContent id="InterfaceMembers">
	// ITcNcTrafo
	virtual HRESULT TCOMAPI Forward(TcNcTrafoParameter* p);
	virtual HRESULT TCOMAPI Backward(TcNcTrafoParameter* p);
	virtual HRESULT TCOMAPI TrafoSupported(TcNcTrafoParameter* p, bool fwd);
	virtual HRESULT TCOMAPI GetDimensions(ULONG* pFwdInput, ULONG* pFwdOutput);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

///<AutoGeneratedContent id="Members">
	double m_ArmLengthA1;
	double m_ArmLengthA2;
	double m_ArmLengthA3;
	double m_ArmOffsetD1;
	double m_ArmOffsetD3;
	double m_ArmOffsetD4;
	double m_ArmOffsetD6;
///</AutoGeneratedContent>
};
