///////////////////////////////////////////////////////////////////////////////
// TC_DriverClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "TC_DriverClassFactory.h"
#include "TC_DriverServices.h"
#include "TC_DriverVersion.h"
#include "SixAxisArticulatedTrafo.h"

BEGIN_CLASS_MAP(CTC_DriverClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_TC_Driver, CID_TC_DriverCSixAxisArticulatedTrafo, SRVNAME_TC_DRIVER "!CSixAxisArticulatedTrafo", CSixAxisArticulatedTrafo)
///</AutoGeneratedContent>
END_CLASS_MAP()

CTC_DriverClassFactory::CTC_DriverClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_TC_DRIVER));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(TC_Driver));
#endif //defined(TCDBG_UNIT_VERSION)
}

