///////////////////////////////////////////////////////////////////////////////
// TC_DriverInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "TC_DriverServices.h"


// https://infosys.beckhoff.com/content/1033/tf5200_trafo_interface/441066123.html?id=2904288695032047534
struct TcNcTrafoParameter {
	ULONG dim_i;    // dim of input vectors (i, d_i, dd_i)
	ULONG dim_o;    // dim of output vectors (o, d_o, dd_o, torque)
	ULONG dim_para; // dim of additional parameter (para)
	const double* i;    // input values parameter (dim_i)
	const double* d_i;
	const double* dd_i;
	double* o;          // output values parameter (dim_i)
	double* d_o;
	double* dd_o;
	double* torque;
	const double* para; // additional parameter (dim_p)
	double payload;     // weight in kg
	double tool_len;    // actual tool length in [mm]
};

//#include "TcNcKinematicsInterfaces.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_05010001_0000_0000_E000_000000000064_INCLUDED_)
#define _TC_TYPE_05010001_0000_0000_E000_000000000064_INCLUDED_
struct __declspec(novtable) ITcNcTrafo : public ITcUnknown
{
	virtual HRESULT TCOMAPI Forward(TcNcTrafoParameter* p)=0;
	virtual HRESULT TCOMAPI Backward(TcNcTrafoParameter* p)=0;
	virtual HRESULT TCOMAPI TrafoSupported(TcNcTrafoParameter* p, bool fwd)=0;
	virtual HRESULT TCOMAPI GetDimensions(ULONG* pFwdInput, ULONG* pFwdOutput)=0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcNcTrafo, IID_ITcNcTrafo);
#endif // !defined(_TC_TYPE_05010001_0000_0000_E000_000000000064_INCLUDED_)

///</AutoGeneratedContent>
