///////////////////////////////////////////////////////////////////////////////
// TC_DriverServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_TC_Driver = 0x3F000000;
#define SRVNAME_TC_DRIVER "TC_Driver"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_TC_DriverCSixAxisArticulatedTrafo = {0xf0a059de,0xa7fb,0x41e4,{0xad,0xbb,0xf9,0x76,0xe6,0xe1,0x7e,0x7b}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataAreaIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_SixAxisArticulatedTrafoArmLengthL1 = 0x00000001;
const PTCID PID_SixAxisArticulatedTrafoArmLengthL2 = 0x00000002;
const PTCID PID_SixAxisArticulatedTrafoArmLengthL3 = 0x00000003;
const PTCID PID_SixAxisArticulatedTrafoArmOffsetD1 = 0x00000004;
const PTCID PID_SixAxisArticulatedTrafoArmOffsetD2 = 0x00000005;
const PTCID PID_SixAxisArticulatedTrafoArmOffsetD3 = 0x00000006;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_05010001_0000_0000_E000_000000000064_INCLUDED_)
#define _TC_IID_05010001_0000_0000_E000_000000000064_INCLUDED_
TCOM_DECL_INTERFACE("05010001-0000-0000-e000-000000000064", ITcNcTrafo)
#endif // !defined(_TC_IID_05010001_0000_0000_E000_000000000064_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
///</AutoGeneratedContent>



///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
